In [1]:
using Plots
using StatsPlots
using JLD2
using MPSTime
using StatsBase
using Measures
using LaTeXStrings
using Pickle
using PyCall

In [2]:
py"""
import pickle
 
def load_pickle(fpath):
    with open(fpath, "rb") as f:
        data = pickle.load(f)
    return data
"""

load_pickle = py"load_pickle"

PyObject <function load_pickle at 0x74775c5d2ac0>

In [28]:
pms = 5:10:95
mmae_kepGD_britsi = Matrix{Float64}(undef, 5, length(pms))
std_kepGD_britsi = Matrix{Float64}(undef, 5, length(pms))

mmae_kepGD_cdrec = Matrix{Float64}(undef, 5, length(pms))
std_kepGD_cdrec = Matrix{Float64}(undef, 5, length(pms))

mmae_kepGD_csdi = Matrix{Float64}(undef, 5, length(pms))
std_kepGD_csdi = Matrix{Float64}(undef, 5, length(pms))

for i in 0:4
    britsi_data = load_pickle("KEPGD_britsi_results_$i.pkl")
    cdrec_data = load_pickle("KEPGD_CDREC_results_$i.pkl")
    csdi_data = load_pickle("KEPGD_CSDI_results_$i.pkl")

    for (j, pm) in enumerate(pms)
        britsi_data_by_fold = mean(britsi_data[pm]; dims=(2,3))
        cdrec_data_by_fold = mean(cdrec_data[pm]; dims=(2,3))
        csdi_data_by_fold = mean(csdi_data[pm]; dims=(2,3))

        mmae_kepGD_britsi[i+1,j] = mean(britsi_data_by_fold)
        std_kepGD_britsi[i+1,j] = std(britsi_data_by_fold)

        mmae_kepGD_cdrec[i+1,j] = mean(cdrec_data_by_fold)
        std_kepGD_cdrec[i+1,j] = std(cdrec_data_by_fold)

        mmae_kepGD_csdi[i+1,j] = mean(csdi_data_by_fold)
        std_kepGD_csdi[i+1,j] = std(csdi_data_by_fold)
    end

end

In [29]:
@save "GD_pyalgs.jld2" mmae_kepGD_britsi std_kepGD_britsi mmae_kepGD_cdrec std_kepGD_cdrec mmae_kepGD_csdi std_kepGD_csdi

In [5]:
pms = 5:10:95
mmae_kepC6_britsi = Matrix{Float64}(undef, 5, length(pms))
std_kepC6_britsi = Matrix{Float64}(undef, 5, length(pms))

for i in 0:4
    britsi_data = load_pickle("KEPC6_britsi_results_$i.pkl")
   

    for (j, pm) in enumerate(pms)
        britsi_data_by_fold = mean(britsi_data[pm]; dims=(2,3))
       

        mmae_kepC6_britsi[i+1,j] = mean(britsi_data_by_fold)
        std_kepC6_britsi[i+1,j] = std(britsi_data_by_fold)

    end

end

In [6]:
@save "C6_britsi.jld2" mmae_kepC6_britsi std_kepC6_britsi 

In [62]:
Xs = rand(100,96)
y_test=rand(50)
ys = vcat(zeros(45), ones(55))

nfolds = 30


30

In [63]:
py"""
from sklearn.model_selection import StratifiedShuffleSplit
sp = StratifiedShuffleSplit(n_splits=$nfolds, test_size=$(length(y_test)), random_state=1)
folds_py = sp.split($Xs, $ys)
"""
folds = collect(py"folds_py")

30-element Vector{Any}:
 ([29, 85, 93, 56, 41, 59, 98, 24, 78, 96  …  35, 32, 77, 65, 23, 30, 91, 10, 19, 17], [9, 94, 5, 1, 67, 69, 95, 48, 63, 38  …  52, 60, 16, 57, 37, 12, 66, 11, 18, 15])
 ([26, 74, 86, 43, 78, 14, 76, 3, 22, 7  …  5, 71, 91, 66, 63, 64, 61, 34, 35, 89], [55, 40, 68, 73, 84, 59, 79, 58, 54, 15  …  75, 8, 32, 10, 81, 60, 90, 87, 44, 85])
 ([51, 20, 5, 18, 74, 76, 65, 77, 91, 3  …  75, 2, 31, 60, 80, 44, 30, 96, 83, 95], [35, 4, 69, 0, 67, 57, 79, 48, 98, 42  …  62, 68, 78, 70, 37, 73, 72, 17, 11, 23])
 ([79, 45, 55, 12, 99, 98, 51, 69, 59, 8  …  36, 25, 61, 53, 54, 81, 67, 97, 92, 80], [76, 63, 37, 90, 0, 83, 73, 72, 48, 17  …  46, 88, 86, 52, 39, 47, 44, 21, 41, 93])
 ([7, 43, 92, 56, 97, 4, 83, 79, 33, 5  …  24, 21, 53, 13, 55, 61, 65, 71, 29, 14], [82, 31, 35, 1, 64, 12, 76, 30, 77, 96  …  34, 84, 85, 41, 0, 16, 20, 6, 38, 40])
 ([62, 74, 21, 84, 30, 60, 83, 5, 17, 15  …  16, 7, 39, 64, 46, 67, 0, 6, 14, 1], [80, 53, 54, 26, 12, 31, 18, 88, 11, 48  …  37, 61, 19

5-element Vector{Any}:
 ([29, 85, 93, 56, 41, 59, 98, 24, 78, 96  …  35, 32, 77, 65, 23, 30, 91, 10, 19, 17], [9, 94, 5, 1, 67, 69, 95, 48, 63, 38  …  52, 60, 16, 57, 37, 12, 66, 11, 18, 15])
 ([26, 74, 86, 43, 78, 14, 76, 3, 22, 7  …  5, 71, 91, 66, 63, 64, 61, 34, 35, 89], [55, 40, 68, 73, 84, 59, 79, 58, 54, 15  …  75, 8, 32, 10, 81, 60, 90, 87, 44, 85])
 ([51, 20, 5, 18, 74, 76, 65, 77, 91, 3  …  75, 2, 31, 60, 80, 44, 30, 96, 83, 95], [35, 4, 69, 0, 67, 57, 79, 48, 98, 42  …  62, 68, 78, 70, 37, 73, 72, 17, 11, 23])
 ([79, 45, 55, 12, 99, 98, 51, 69, 59, 8  …  36, 25, 61, 53, 54, 81, 67, 97, 92, 80], [76, 63, 37, 90, 0, 83, 73, 72, 48, 17  …  46, 88, 86, 52, 39, 47, 44, 21, 41, 93])
 ([7, 43, 92, 56, 97, 4, 83, 79, 33, 5  …  24, 21, 53, 13, 55, 61, 65, 71, 29, 14], [82, 31, 35, 1, 64, 12, 76, 30, 77, 96  …  34, 84, 85, 41, 0, 16, 20, 6, 38, 40])

In [58]:
folds[1][1]

50-element Vector{Int64}:
 29
 85
 93
 56
 41
 59
 98
 24
 78
 96
  ⋮
 32
 77
 65
 23
 30
 91
 10
 19
 17